Do not try to re-open last password file with biometrics when file is closed
authpass/authpass pull request #173
Opened 2020-10-02 13:55 UTC by Trekky12

After closing a password file the biometric prompt is shown and the last password file is still opened afterwards.
With this change the biometric prompt is shown (apparently needed to delete from the biometric storage) and afterwards the main screen is shown.
The biometric prompt for opening of the last password file is no longer shown.

When the file is only unlocked and not closed the biometric prompt for opening is still shown.

2020-10-02 14:02 UTC, hpoul commented
Good point, but actually the user should not end up on this screen in the first place, in other places this is already checked..
I'll look at it later (afk right now), but i think it would be better to have a helper method which created a route which either opens the unlock screen, or the select file screen.. I'm not sure if something like this already exists

2020-10-02 17:11 UTC, hpoul requested changes
I think a better approach would be to have `LockedScreen.navigate` which takes a `KdbxBloc` as parameter, and either navigates to itself if there are files in quick unlock or otherwise forward to `SelectFileScreen.navigate`.

what do you think?

2020-10-02 17:24 UTC, Trekky12 commented
Honestly I don't exactly understand what you mean. What do you mean with "actually the user should not end up on this screen in the first place"?

Which screen should be shown when "close password files" on the lock screen is pressed? Which screen should be shown when the "Unlock files" is pressed?

2020-10-02 17:37 UTC, hpoul commented
> Which screen should be shown when "close password files" on the lock screen is pressed? Which screen should be shown when the "Unlock files" is pressed?

Maybe we have some misunderstanding here.. if I understand the change correctly.. right now.. user has a file open, without quick unlock.. selects 'lock files' and will end up in the lock screen. Your change now immediately forwards the user to the `SelectFileScreen` - right?

what I'm saying is, that the user should not end up on the `LockedScreen` in the first place, after tapping 'lock files' without having quick unlock enabled. but the 'lock files' screen should instead directly navigate to the `SelectFileScreen`

2020-10-02 17:44 UTC, Trekky12 commented
Actually my fix was another case.
The user has a file open with quickunlock enabled (biometric protection enabled). When locking the file the lock screen is shown. When "close password files" is selected to close the file and remove quickunlock by clearing the biometric storage the select file screen is shown (correct in my opinion).
Unfortunately right after the app navigates to the select file screen the app tries to open the last selected file with quickunlock (biometric prompt is shown). 
My change prevents this biometric prompt after closing the file. 

Actually I didn't test the change without quickunlock enabled.

2020-10-02 18:01 UTC, hpoul commented
I don't quite understand the problem. Here is a screencast with the latest version:

1. Enter master password with quick unlock to open the file
2. Select Lock from the database and end up on the lock screen
3. Click 'Unlock' and correctly see the biometric unlock.
4. Select Lock again
5. This time press 'Close Password Files' and I end up on the select file screen, without any prompts.

isn't `5` exactly what you describe how it should be?

![Untitled 2020-10-02 19_58_10](https://user-images.githubusercontent.com/313066/94954827-ef15b380-04e9-11eb-883b-b15fd1b6fa3d.gif)

2020-10-02 18:07 UTC, Trekky12 commented
Yes in my opinion this should be the correct behaviour. Unfortunately in the Android Emulator and on my Huwai device the latest version from master does show the biometric prompt after closing the file (like unlock).

Is it possible that this is an Android related problem (I see you use the iOS version)?

2020-10-02 19:27 UTC, hpoul commented
okay I think I understand the problem.. kind of.. 

<img width="649" alt="Screen Shot 2020-10-02 at 21 23 18" src="https://user-images.githubusercontent.com/313066/94961726-816f8480-04f5-11eb-828c-65aada24e1bf.png">

<-- the selected line triggers a rebuild of the screen.. probably on iOS the clear for biometric storage is fast enough, that it is cleared before the user ends up on the `SelectFileScreen`, while on android we land on the home screen before it is cleared.. that's a valid problem, but I think we should fix it at the root of the problem.. because i think as your PR is right now, it would simply not "redirect" the user to the home screen, if there is no quick unlock at all.

i think it would be enough to just move that `_openedFiles.value = OpenedKdbxFiles({});` line to the end of the method 😅️ because then the biometric storage should have been cleared for sure. if you like you could give it a try, otherwise i'll try it tomorrow

2020-10-02 20:33 UTC, Trekky12 commented
That sounds like the right approach. I noticed that the screen is rebuild but apparently couldn't find the right position. Of course the root of the problem should be fixed. My PR is apparently only a workaround which doesn't respect files without quickunlock. 

I'm currently not able to test this, so feel free to test your idea 👍

2020-10-03 16:20 UTC, Trekky12 commented
Hey @hpoul,
I changed the location of the mentioned `_openedFiles.value = OpenedKdbxFiles({});` and it is working now correctly on my device 👍

2020-10-03 17:23 UTC, merged

2020-10-03 17:26 UTC, hpoul commented
nice, 👍️ thanks for testing  😁️